### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by congressclerk** [HenrikJoreteg/humanjs#10]
Henrik, quick question - what exactly is line 42 "var id = 7;" in fakeApi.js doing for the collection?

**Comment by HenrikJoreteg** [comment]
The whole fakeApi thing is just some server code to simulate a real API.
That particular line is just the starting point for auto-incrementing IDs
(used here:
https://github.com/HenrikJoreteg/humanjs/blob/master/template/fakeApi.js#L54)
.

Backbone Collections assume that your model IDs are unique, so I'm just
making sure that new ones that get created start with a unique number
(since I hardcoded 1 - 6 right above:
https://github.com/HenrikJoreteg/humanjs/blob/master/template/fakeApi.js#L4-L40
)

Hope that makes sense. In a real app, you'd have a real API with a real
database that ensured you had unique IDs. This was just the simplest way to
demonstrate interactions with an API without requiring you to install or
run a database.

**Comment by congressclerk** [comment]
Ah okay, awesome.  So it's just needed for the random generation. Makes sense
